FROM docker.io/fedora:33

# Install all deps in the standard repos
RUN dnf -y install git zip unzip nodejs make gcc gcc-c++ gettext findutils wget

RUN mkdir /opt/almond

RUN useradd almond && \
   chown almond:almond /opt/almond
USER almond
COPY --chown=almond:almond . /opt/almond
WORKDIR /opt/almond

RUN npm ci && rm -fr /home/almond/.cache && rm -fr /home/almond/.npm
RUN mkdir /home/almond/.cache

EXPOSE 3000
ENTRYPOINT ["npm", "start"]
